# Site settings
title: A basic Jekyll site
email: your-email@domain.com
description: "a basic jekyll site."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
